modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Improved%20Sign%20Editing"
logoFile="icon.png"

[[mods]]
modId="improvedsignediting"
version="1.0"
displayName="Improved Sign Editing"
displayURL="https://serilum.com/mod/improved-sign-editing"
authors="Rick South"
description='''Improves the functionality of editing signs, automatically go to the next and previous line.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Adam E, Alister, aternosorg, Cherriesaurus, FireStriker, Greg Johnson, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Shana Gitnick, silver Bowsman, Tyler Behl   

If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.improvedsignediting]]
    modId="collective"
    mandatory=true
    versionRange="[7.23,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.improvedsignediting]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.2]"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config = "improvedsignediting_neoforge.mixins.json"